### PR TITLE
graphql-timeline-and-hotfix

### PR DESCRIPTION
**Pull request by PrivacyDevel**

### CODE REVIEW

**Comment by DrSocket** [comment]
@PrivacyDevel having an issue merging and compiling this pr because 
import routes/[
  preferences, timeline, status, media, search, rss, list, debug,
  unsupported, embed, resolver, router_utils]
  
 but timeline.nim was removed

**Comment by DrSocket** [comment]
@PrivacyDevel this pr is not compatible as is with nsfw branch right?

**Comment by PrivacyDevel** [comment]
@DrSocket No, it unfortunately isn't. I merged it all in my graphql branch but threads currently disappear when you're logged in.

**Comment by PrivacyDevel** [comment]
Closed in favor of #2

**Pull request closed without merging**
